import Head from "next/head";

const Header = () => {
    return(
        <Head>
            <title>공공 임대 주택 현황</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
    )
}

export default Header;